### ISSUE TITLE
Request: Add romsets.xml (Neo Geo) to downloader

### ISSUE THREAD

**Issue by GittaHub** [MiSTer-devel/Downloader_MiSTer#12]
Would be very handy to have https://github.com/MiSTer-devel/NeoGeo_MiSTer/blob/master/releases/romsets.xml included to downloader.

**Comment by theypsilon** [comment]
Hey! It's already happening as you can see here: https://github.com/MiSTer-devel/Distribution_MiSTer/tree/main/games/NEOGEO
