### ISSUE TITLE
mra_alternatives don't seem to get updated

### ISSUE THREAD

**Issue by lagomorph** [MiSTer-devel/Downloader_MiSTer#14]
If the hash for the mra_alternatives summary file doesn't match the newest, mra_alternatives_summary.json.zip gets downloaded and the hashes are updated in the store (summary and files) but the files themselves aren't updated.

**Comment by theypsilon** [comment]
Hey, thanks for the heads up, but that's not very relevant. Changes in the summary file doesn't necessarily mean changes in the files. Because it's a zip and the hash is computed with some added metadata.

If you see a MRA that didn't get updated, please let me know.

**Comment by lagomorph** [comment]
None of the Donkey Kong MRAs changed [here](https://github.com/MiSTer-devel/MRA-Alternatives_MiSTer/commit/801ee4c235485057c8837f2acc0591c5711db9e0) update. Those changes are reflected in the summary and contents files.

It updated the hashes in my local store with the latest but the files are not updated.

**Comment by theypsilon** [comment]
Could you please provide me this file? Scripts/.config/downloader/downloader.json.zip
I've just checked is working on my setup.

**Comment by lagomorph** [comment]
[downloader.json.zip](https://github.com/MiSTer-devel/Downloader_MiSTer/files/7998017/downloader.json.zip)

**Comment by theypsilon** [comment]
Your local store seems to be correct:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/852246/152427078-03b03873-7055-43d2-8bfa-7e4530e22120.png">

This is the file in my setup:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/852246/152427025-b6df9293-30e4-4cf8-bc31-377f80b36325.png">

It matches with what you see here: https://github.com/MiSTer-devel/Distribution_MiSTer/blob/main/_Arcade/_alternatives/_Donkey%20Kong/Donkey%20Kong%20(2%20marios)%20-%20HBMame.mra

**Comment by lagomorph** [comment]
Thanks for verifying. In my case I have the old file still:

/media/fat# md5sum _Arcade/_alternatives/_Donkey\ Kong/Donkey\ Kong\ \(2\ marios\)\ -\ HBMame.mra 
4507bea9214f305ff56a861941c2b74d  _Arcade/_alternatives/_Donkey Kong/Donkey Kong (2 marios) - HBMame.mra

I wonder if you tested the update with a fresh store or one that was from before the changes were made in mra_alternatives. If I manually alter the hash of the summary file in the local store and the hashes of the MRA files in the local store shouldn't an update force an update of my files? In my case all that happens is that the summary file downloads and all the hashes are updated *but the files aren't*.

**Comment by theypsilon** [comment]
I have an old setup, so I got it updated for sure. It's the very first time I see this problem happening, maybe there is some corner case that needs to be covered. Do you have a standard setup? Do you use usb0? Do you use CIFS? Anything unusual?

If you saved that downloader.json file with a different hash for the `_Arcade/_alternatives/_Donkey\ Kong/Donkey\ Kong\ (2\ marios)\ -\ HBMame.mra` file, you should see it being updated, even when there are no changes in the summary.

**Comment by lagomorph** [comment]
Interesting. No, I'm not using usb0, CIFS, or anything unusual that I can think of. I have a standard download.ini. Nothing looks weird in the file system.

If I modify only the file hash in downloader.json.zip nothing gets updated (even the file hash). If I modify the file hash and the summary file hash I get both the file hash and the summary hash updated to the latest but still no file update.

I can simply blow away the files, have them update (I've verified that works), and see what happens on the next mra_alternatives update. Maybe there's something else in my store that's wonky.

**Comment by theypsilon** [comment]
You could also delete your local store (wiping downloader.json.zip entirely) for fixing the issue. It would get recreated again in the next run.

I'd like to investigate how did you end up in that state, though. Is there anything unusual in your ini file? Maybe you could also share your log to see what are all the variables.

**Comment by lagomorph** [comment]
downloader.ini just has some other DBs and verbose = True
If you're interested, there's the downloader.json.zip where I modified the file hash on the one MRA. For me, this caused no update, even to the hash. The log is from when I changed both the MRA file hash and summary file hash.

[downloader.ini.txt](https://github.com/MiSTer-devel/Downloader_MiSTer/files/7998946/downloader.ini.txt)

[downloader.log](https://github.com/MiSTer-devel/Downloader_MiSTer/files/7998933/downloader.log)

[downloader.json.zip with modified hash](https://github.com/MiSTer-devel/Downloader_MiSTer/files/7998957/downloader.json.zip)

**Comment by lagomorph** [comment]
With the changes you made over the weekend if I change the hash of the summary file in the local store it now does detect a checksum mismatch on the file and downloads it:

`Downloading 1 files:
_Arcade/_alternatives/_Donkey Kong/Donkey Kong (2 marios) - HBMame.mra: a2a144f64041899175105f4b0f7a5ec6 != 4507bea9214f305ff56a861941c2b74d
_Arcade/_alternatives/_Donkey Kong/Donkey Kong (2 marios) - HBMame.mra
*.
`

It still doesn't update the file if only the file's hash is changed in the local store (summary file hash left alone) but the summary file hash is going to change if a file changes so I don't think that's an issue.

**Comment by theypsilon** [comment]
Good to know that I fixed that. Let me know if you find any other issue, and thanks a lot for testing it!
