### ISSUE TITLE
Question: Save updates to /media folder without appending _Consoles/_Arcade/etc folders

### ISSUE THREAD

**Issue by Chromagram** [MiSTer-devel/Downloader_MiSTer#15]
Hi there,

Is there any way to set the downloader to update and install the files I want straight into the /media folder instead of adding the associated _Console folder or any other similar folder? I don't use a ton of cores so I'd love to just run the script and keep everything clean. This way, I can just boot the MiSTer, and immediately see the cores in the list without entering additional directories.

(Unless this is already possible)

**Comment by theypsilon** [comment]
If you are experienced in programming, you could set your own custom database to have that structure: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/custom-databases.md

**Comment by Chromagram** [comment]
I have baseline knowledge of coding, so I don't think this route will go best for me. It's not a major inconvenience, so I'll stick with the additional directories. Thanks :)

**Comment by theypsilon** [comment]
No worries!
