### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Dankoman** [MiSTer-devel/Downloader_MiSTer#19]
When I try to run aupdate from the MiSTer menu the part where it updates the CA-certs work.
But after that it fails.

```
The script will run normally now:
Running MiSTer Downloader

bash: line 122: BASH_SOURCE[0]: unbound variable
Press any key to continue
```

**Comment by theypsilon** [comment]
Hey! How do you run it? Do you execute this on MiSTer? Please, provide all the info about your running environment.

**Comment by Dankoman** [comment]
I have tried both from MiSTer F12 -> Scripts -> Update
And by connecting with SSH this is the complete output

```
/root# /media/fat/Scripts/update.sh
Downloading and executing
mister_updater.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
WARNING: The version of Update.sh you are using is now deprecated!
Please update to the latest updater located at the link below.
https://github.com/MiSTer-devel/Downloader_MiSTer
100  4920  100  4920    0     0   6722      0 --:--:-- --:--:-- --:--:--  6722
The script will run normally now:
Running MiSTer Downloader

bash: line 122: BASH_SOURCE[0]: unbound variable
/root#

```

**Comment by theypsilon** [comment]
Please follow the setup process from here: https://github.com/MiSTer-devel/Downloader_MiSTer#setup-and-usage

**Comment by Dankoman** [comment]
Ok, to be clear.
I have a working system that has been up an running, including  regular updates every week or so, for more than a year.
But when I tried to update 2-3 days ago I started getting this error. I have already tried replace the downloader.sh file manually to no avail...
My guess is that there is something that goes wrong on line 115
`export DOWNLOADER_LAUNCHER_PATH="${BASH_SOURCE[0]}"`
leaving DOWNLOADER_LAUNCHER_PATH empty or something?
What should that path be for a vanilla stock install? Maby I can try and "hard" set it?

**Comment by theypsilon** [comment]
To start from scratch you should use Mr Fusion: https://github.com/MiSTer-devel/mr-fusion
Before don't forget to backup your data.

The error is clear, your system somehow doesn't interpolate BASH_SOURCE. This is not a common problem. It means something wrong in your shell beyond hotfixes. I recommend starting fresh.

**Comment by Dankoman** [comment]
I was starting think along those lines aswell. 
Well that is what weekends are for right ;)
