### ISSUE TITLE
Won't read from /media/fat/downloader.ini

### ISSUE THREAD

**Issue by djvj1** [MiSTer-devel/Downloader_MiSTer#20]
Readme says to use this ini to make changes, but it never reads from it. It's only looking at this one according to my log:
Reading file: /media/fat/Update/MiSTer_Downloader/downloader.ini

My ini:
https://pastebin.com/DNPrxXEJ

Log:
https://pastebin.com/1HwS6gh8

I set verbose to true and log says it's false
Also tried moving the ini to "/media/fat/Update/MiSTer_Downloader/downloader.ini" and it still doesn't read it.

**Comment by theypsilon** [comment]
Hey, place downloader.sh at /media/fat/Scripts/downloader.sh and try again.

**Comment by djvj1** [comment]
Thank you, that did work! I still had it in
Scripts/Update/Mister_Downloader/
