### ISSUE TITLE
error: invalid zip file with overlapped components (possible zip bomb)

### ISSUE THREAD

**Issue by LuoJohnT** [MiSTer-devel/Downloader_MiSTer#21]
I started receiving errors when trying to update today.  Unzip is throwing an exception because it is recognizing the downloaded file as malicious.  I am running the latest version of download.sh.  The same issue occurs with any update script which downloads zipped files.  Previously had no issues updating. 

> /root# cat /media/fat/Scripts/.config/downloader/downloader.log
> START!
> 
> Reading file: /media/fat/downloader.ini
> Reading 'distribution_mister' db section
> Reading 'jtcores' db section
> env: {
>     "DOWNLOADER_LAUNCHER_PATH": "/media/fat/Scripts/downloader.sh",
>     "DOWNLOADER_INI_PATH": null,
>     "CURL_SSL": "--cacert /etc/ssl/certs/cacert.pem",
>     "COMMIT": "856b6d5",
>     "ALLOW_REBOOT": null,
>     "UPDATE_LINUX": "true",
>     "DEFAULT_DB_URL": "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip",
>     "DEFAULT_DB_ID": "distribution_mister",
>     "DEFAULT_BASE_PATH": null,
>     "DEBUG": "false",
>     "FAIL_ON_FILE_ERROR": "false"
> }
> config: {
>     "databases": {
>         "distribution_mister": {
>             "db_url": "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip",
>             "section": "distribution_mister"
>         },
>         "jtcores": {
>             "db_url": "https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip",
>             "section": "jtcores"
>         }
>     },
>     "config_path": "/media/fat/downloader.ini",
>     "base_path": "/media/fat",
>     "base_system_path": "/media/fat",
>     "storage_priority": "prefer_sd",
>     "allow_delete": 1,
>     "allow_reboot": 1,
>     "update_linux": true,
>     "parallel_update": true,
>     "downloader_size_mb_limit": 100,
>     "downloader_process_limit": 300,
>     "downloader_timeout": 300,
>     "downloader_retries": 3,
>     "zip_file_count_threshold": 60,
>     "zip_accumulated_mb_threshold": 100,
>     "filter": null,
>     "verbose": false,
>     "debug": false,
>     "default_db_id": "distribution_mister",
>     "start_time": 1654702379.9457989,
>     "user_defined_options": [],
>     "curl_ssl": "--cacert /etc/ssl/certs/cacert.pem",
>     "update_linux_environment": 0,
>     "fail_on_file_error": false,
>     "commit": "856b6d5"
> }
> cacert file at "/etc/ssl/certs/cacert.pem" seems to be fine.
> Loading db from url: https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip
> Loading db from url: https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip
> Downloading 2 files:
> /tmp/temp_filet7etzsji
> /tmp/temp_filex45tz6id
> *..
> 
> Checking hashes...
> ++
> subprocess.run unzip -p /tmp/temp_filet7etzsji Return Code was '12'
> 
> error: invalid zip file with overlapped components (possible zip bomb)
> 
> Could not load json from "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip"
> subprocess.run unzip -p /tmp/temp_filex45tz6id Return Code was '12'
> 
> error: invalid zip file with overlapped components (possible zip bomb)
> 
> Could not load json from "https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip"
> Skipping local_store saving...
> 
> ===========================
> Downloader 1.5 (856b6d5) by theypsilon. Run time: 0:00:02.29s
> Log: /media/fat/Scripts/.config/downloader/downloader.log
> 
> Installed:
> none.
> 
> Errors:
> https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip, https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip
> 
> linux_descriptions_count: 0
> Length of failed_dbs: 2

**Comment by theypsilon** [comment]
This error only happens with a Linux version from September 2021. Are you using a SD card with that Linux version?

**Comment by LuoJohnT** [comment]
That sounds right.  I don't keep the box connected unless I update it for a given feature. The last time I updated was around when Jotego released his CPS2 cores.  My kernel version is "5.13.12-MiSTer".  Is there an update path using the self updating script for cases where the device is not kept connected?

**Comment by LuoJohnT** [comment]
After some troubleshooting I was able to solve the issue with the following steps:

1.  Download mister_updater.sh ([v4.0.17](https://github.com/MiSTer-devel/Updater_script_MiSTer/blob/a5f5d0916349f6433ea92c0c069cf5361b9caf3a/mister_updater.shl))
2. Directly run the script to update the kernel to 5.15.1-MiSTer
3. Switch to new downloader script to bring device current

Is it possible for you to do a check of the linux version and update first if required?  Thanks!

**Comment by theypsilon** [comment]
Glad that you managed to update your Linux version! Regarding your question, yes, it's indeed possible. I'm personally not able to expend time on it since my backlog is already pretty full with other tasks. But PRs are very welcomed, would you be willing to work on it?

**Comment by theypsilon** [comment]
This should be fixed in any Linux version from after September 2021
