### ISSUE TITLE
Condensing multiple consecutive spaces in mra filename into a single space

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/Downloader_MiSTer#28]
Condensing multiple consecutive spaces into a single space.
This was fixed with the [old mister_updater.sh script](https://github.com/MiSTer-devel/Updater_script_MiSTer) but was lost with the new Downloader.

See https://github.com/MiSTer-devel/Updater_script_MiSTer/pull/71/commits/5dfccfa5aa05cb3f09124dd6d3bd5ba9e74af36d

Some examples of filenames with double-spaces in filenames:
```
Magic Sword  Heroic Fantasy -World 900725-.mra
Mega Man  The Power Battle -CPS1, USA 951006-.mra
Quiz & Dragons  Capcom Quiz Game -USA 920701-.mra
Quiz Tonosama no Yabou 2  Zenkoku-ban -Japan 950123-.mra
Street Fighter II'  Champion Edition -World 920513-.mra
Street Fighter II'  Hyper Fighting -World 921209-.mra
Street Fighter II  The World Warrior -World 910522-.mra
```

**Comment by theypsilon** [comment]
Hey, thanks for the suggestion. This should be fixed (if considered a problem) in the name of the files itself. The distribution of binaries should't have opinions on how binaries or MRAs are named and give total freedom (and responsability) to cores and MRA maintainers.

You should open a GitHub issue in each respective repository where you think names could be improved.
