### ISSUE TITLE
Issue wit pc downloader

### ISSUE THREAD

**Issue by RolandKaechele** [MiSTer-devel/Downloader_MiSTer#29]
Hi,

I get the following error from https://github.com/MiSTer-devel/Downloader_MiSTer/releases/download/latest/downloader.zip

{code}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\TEMP\roka\2\tmp2bdrzqig.zip\__main__.py", line 49, in <module>
NameError: name 'exit' is not defined
{code}

sys.exit instead of exit is needed

**Comment by RolandKaechele** [comment]
[patched_file.zip](https://github.com/MiSTer-devel/Downloader_MiSTer/files/10136215/patched_file.zip)

**Comment by theypsilon** [comment]
Thanks for reporting it, fixed at https://github.com/MiSTer-devel/Downloader_MiSTer/commit/2066b9c2fae82130e24d04d6aadbdb5fb664f939
