### ISSUE TITLE
Filtering Question

### ISSUE THREAD

**Issue by Chromagram** [MiSTer-devel/Downloader_MiSTer#31]
Hello, I'm just curious about a filtering issue I'm having. I'm sure I'm not doing it correctly but I'd like to know how to remedy this.

Right now, my downloader.ini file looks like this:

[mister]
filter = gb gameboy2p gba gba2p gamegear genesis megacd nes psx s32x sms snes tgfx16 wonderswan

However, after running the downloader, I keep getting the Mega Duck and the Pocket Challenge V2 installed as well. Where are these two coming from?

Many thanks.

**Comment by theypsilon** [comment]
Hey, MegaDuck is coming from GameBoy, is an MGL. You may add a negative term for that "!megaduck" or a more general one against MGLs "!mgl". I don't know what  Pocket Challenge V2 is, I'll check in a bit.

**Comment by theypsilon** [comment]
Pocket Challenge V2 is a MGL for WonderSwan, you may filter it out too with `!pocketchallengev2`
