### ISSUE TITLE
Adding "!genesis" deletes the new Megadrive(Nuked) core, too.

### ISSUE THREAD

**Issue by vanfanel** [MiSTer-devel/Downloader_MiSTer#43]
Hi there!

It seems that adding `!genesis` in downloader.ini, both the old Genesis and the new Nuked Megadrive cores are deleted.
Shouldn't `!genesis` uninstall the old Genesis core only, while keeping the new MegaDrive one? 
I mean, there's `!megadrive`, which supposedly uninstalls/ignores the MegaDrive core, right?

**Comment by matijaerceg** [comment]
@vanfanel looks like you posted this issue twice

Anyway, I came to post the same issue - I think unless the genesis core gets deprecated, the filters should work separately, and !genesis should not remove the megadrive core

**Comment by matijaerceg** [comment]
So, it would appear that https://github.com/MiSTer-devel/Distribution_MiSTer/blob/main/db.json.zip has both cores using tag 16, and tags `genesis` and `megadrive` are both # 16 ... so @theypsilon maybe you can confirm, but there's nothing to be done about this with the downloader, it's a MiSTer official distribution issue?

![image](https://github.com/MiSTer-devel/Downloader_MiSTer/assets/4306199/1ac6e6bd-8277-4d2a-9d28-17878f4a0ca3)

![image](https://github.com/MiSTer-devel/Downloader_MiSTer/assets/4306199/01f73707-591b-46e8-9657-fc5c6bc5c288)

**Comment by hi0t** [comment]
This really doesn't seem logical. Even if we want to install both cores, we can simply write in the filter - genesis, megadrive. But it is not possible to install only one of them.

**Comment by littlegamer87** [comment]
I support this issue. The downloader does not allow to choose which megadrive/genesis core to install, they are treated synonymous.

**Comment by theypsilon** [comment]
Hey! This is already supported, use !genesis-core to remove the old core, or !megadrive-core to remove the new core.

**Comment by vanfanel** [comment]
@theypsilon Gracias amigo! :)
