### ISSUE TITLE
downloader_pc_launcher.py not working

### ISSUE THREAD

**Issue by ZXTFINAL** [MiSTer-devel/Downloader_MiSTer#44]
downloader_pc_launcher.py not working

**Comment by theypsilon** [comment]
Hey @ZXTFINAL , could you please provide a bit more context? 
- Which OS you are using
- Did you try on different days?
- Did you see any log?
- Is there anything showing up on screen?

**Comment by ZXTFINAL** [comment]
![image](https://github.com/MiSTer-devel/Downloader_MiSTer/assets/53009474/6f859802-b36b-47b2-983a-8e95083bd9c2)
linux

**Comment by theypsilon** [comment]
You need python3 >= 3.9

Type python -V to check the version. There is a chance that if you use python3 in the cli, you have a higher version.

Let me know if that helps

**Comment by birdybro** [comment]
Just a heads up, Python 3.12+ won't work either because [distutils](https://docs.python.org/3.10/library/distutils.html) was deprecated. [setuptools](https://setuptools.pypa.io/en/latest/) is supposed to be used moving forward.

3.9.x --> 3.11.x still work (I just tested a second time after downgrading to 3.11).

**Comment by theypsilon** [comment]
> Just a heads up, Python 3.12+ won't work either because [distutils](https://docs.python.org/3.10/library/distutils.html) was deprecated. [setuptools](https://setuptools.pypa.io/en/latest/) is supposed to be used moving forward.
> 
> 3.9.x --> 3.11.x still work (I just tested a second time after downgrading to 3.11).

Good catch, fixed it here: https://github.com/MiSTer-devel/Downloader_MiSTer/commit/c08b81c1f95ddfa79d1b544b55236b740c51a954
