### ISSUE TITLE
Detect loading of beta.bin and filtering MRA files based on that

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Downloader_MiSTer#6]
This functionality will make life easier for developers and users as a single repository could be used for beta and non-beta cores.

**Comment by theypsilon** [comment]
How would you suggest the file be detected? The custom download filters feature will be able to do this, but users will have to manually select wich filters they want.

**Comment by theypsilon** [comment]
Database-scoped filters and database-scoped default options could be used to address this already.
